/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rms;

import com.sun.glass.ui.swt.CustomTransfer;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.Image;

/**
 *
 * @author vedant
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txt_password = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btn_Login = new javax.swing.JButton();
        lbl_error = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel5.setBackground(new java.awt.Color(29, 29, 29));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(29, 29, 29));
        jPanel7.setForeground(new java.awt.Color(0, 80, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Email");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 62, -1, -1));
        jPanel7.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 124, 469, 10));

        txt_email.setBackground(new java.awt.Color(29, 29, 29));
        txt_email.setForeground(new java.awt.Color(237, 240, 247));
        txt_email.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_email.setCaretColor(java.awt.Color.white);
        txt_email.setName("txt_email"); // NOI18N
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel7.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 99, 469, -1));

        jLabel2.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Password");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 140, 132, -1));
        jPanel7.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 208, 470, 10));

        txt_password.setBackground(new java.awt.Color(29, 29, 29));
        txt_password.setForeground(new java.awt.Color(237, 240, 247));
        txt_password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_password.setCaretColor(java.awt.Color.white);
        txt_password.setMinimumSize(new java.awt.Dimension(2, 21));
        jPanel7.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 183, 470, -1));

        jComboBox1.setBackground(new java.awt.Color(29, 29, 29));
        jComboBox1.setForeground(new java.awt.Color(29, 29, 29));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Builder", "Engineer", "Customer" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel7.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 236, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("User Type");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 236, -1, -1));

        btn_Login.setBackground(new java.awt.Color(74, 164, 255));
        btn_Login.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 14)); // NOI18N
        btn_Login.setForeground(new java.awt.Color(254, 254, 254));
        btn_Login.setLabel("Login");
        btn_Login.setName("btn_login"); // NOI18N
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });
        jPanel7.add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 295, -1));

        lbl_error.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 13)); // NOI18N
        lbl_error.setForeground(java.awt.Color.blue);
        jPanel7.add(lbl_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 276, 140, 20));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 78, -1, 360));

        panel1.setBackground(new java.awt.Color(29, 29, 29));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rms/1.jpg.jpg"))); // NOI18N

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 78, -1, 341));

        jPanel1.setBackground(new java.awt.Color(85, 85, 85));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rms/icons/icons8-apartment-96.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 1, 100, 70));

        jLabel5.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("REAL ESTATE MANAGEMENT SYSTEM");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 800, 50));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1102, 80));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        // TODO add your handling code here:
        boolean authenticated=false;
        int index=jComboBox1.getSelectedIndex();
        String email=txt_email.getText().trim();
        String password=new String(txt_password.getPassword());
        if(index==0){
            try{
             ManagerOperations managerObject=new ManagerOperations();
             authenticated= managerObject.authenticate(email,password);
             if(authenticated){
                 ManagerHome manager=new ManagerHome(email);
                 this.setVisible(false);
                 manager.setVisible(true);
             }
             else {
                 lbl_error.setText("invalid details");
             }
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(this, e);
            }
            
        }
        else if(index==1){
           try{
             BuilderOperation build=new BuilderOperation();
             authenticated= build.authenticate(email,password);
             if(authenticated){
                 BuilderHome builder=new BuilderHome(email);
                 this.setVisible(false);
                 builder.setVisible(true);
             }
             else {
                 lbl_error.setText("invalid details");
             }
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
        else if(index==2){
            EngineerOperations eng=new EngineerOperations();
            try{
                authenticated=eng.authenticate(email, password);
                 if(authenticated){
                 EngineerHome engHome=new EngineerHome(email);
                 this.setVisible(false);
                 engHome.setVisible(true);
             }
            else {
                
                 lbl_error.setText("invalid details");
             }
               
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(this, e);
            }
            
            
        }
        else if(index==3){
            CustomerOperations eng;
            try{
                eng=new CustomerOperations();
                authenticated=eng.authenticate(email, password);
                 if(authenticated){
                 CustomerHome engHome=new CustomerHome(email);
                 this.setVisible(false);
                 engHome.setVisible(true);
             }
            else {
                
                 lbl_error.setText("invalid details");
             }
               
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(this, e);
            }
            
            
        }
        
        
        
        
        
    }//GEN-LAST:event_btn_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Login;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField txt_email;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
} 
