/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rms;
import java.sql.*; 

import java.awt.Color;
import java.net.ConnectException;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.*;
/**
 *
 * @author vedant
 */
public class ManagerHome extends javax.swing.JFrame {

    /**
     * Creates new form ManagerHome
     */
    Connection conn;
    int managerId;
    String email;
    String name;
    public ManagerHome(String email) {
        this.email=email;
        String username="vedant ";
        String password="pepsin212";
        String address="jdbc:oracle:thin:@192.168.56.101:1521:xe";
        try{
            conn=DriverManager.getConnection(address,username,password);  
        }
        catch(SQLException e){
            System.out.println(e);
        }
        initComponents();
        try{
            ManagerOperations obj=new ManagerOperations();
            String details[]=obj.getManagerDetails(email);
            this.managerId=Integer.parseInt(details[1]);
            this.name=details[0];
            lblName.setText(name);
            lblEmail.setText(email);
            lblId.setText(Integer.toString(managerId));
        }
        catch (Exception e){
        }
        indicator1.setOpaque(true);
        indicator2.setOpaque(true);
        indicator3.setOpaque(true);
        {
//             DefaultTableModel dtm = new DefaultTableModel(0, 0);
//             jTable1.setModel(dtm);
//             dtm.addRow(new Object[]{"fdsj",12});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        button1 = new javax.swing.JPanel();
        indicator1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonHome1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        button2 = new javax.swing.JPanel();
        indicator2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        button4 = new javax.swing.JPanel();
        indicator3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cardParent = new javax.swing.JPanel();
        homeCard = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        addEmployeeCard = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        addEmpParent = new javax.swing.JPanel();
        Engineer = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        nameTxt6 = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        EngineerIdxt3 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jSeparator26 = new javax.swing.JSeparator();
        emailTxt4 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        nameTxt7 = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();
        addressTxt3 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jSeparator28 = new javax.swing.JSeparator();
        jLabel44 = new javax.swing.JLabel();
        Builder_idTxt5 = new javax.swing.JTextField();
        jSeparator29 = new javax.swing.JSeparator();
        confirm4 = new javax.swing.JButton();
        jSeparator30 = new javax.swing.JSeparator();
        Customer = new javax.swing.JPanel();
        nameTxt10 = new javax.swing.JTextField();
        emailTxt6 = new javax.swing.JTextField();
        flatnoTXT = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jSeparator37 = new javax.swing.JSeparator();
        customerIdtxt = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jSeparator38 = new javax.swing.JSeparator();
        jSeparator39 = new javax.swing.JSeparator();
        projectIdTxt = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jSeparator40 = new javax.swing.JSeparator();
        jLabel55 = new javax.swing.JLabel();
        projectIdtxt = new javax.swing.JTextField();
        jSeparator41 = new javax.swing.JSeparator();
        confirm6 = new javax.swing.JButton();
        jSeparator42 = new javax.swing.JSeparator();
        Labour = new javax.swing.JPanel();
        Builder1 = new javax.swing.JPanel();
        nameTxt11 = new javax.swing.JTextField();
        emailTxt7 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jSeparator43 = new javax.swing.JSeparator();
        EngineerIdxt5 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jSeparator44 = new javax.swing.JSeparator();
        jSeparator45 = new javax.swing.JSeparator();
        jSeparator46 = new javax.swing.JSeparator();
        Builder_idTxt7 = new javax.swing.JTextField();
        confirm7 = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();
        Builder = new javax.swing.JPanel();
        nameTxt8 = new javax.swing.JTextField();
        emailTxt5 = new javax.swing.JTextField();
        nameTxt9 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jSeparator31 = new javax.swing.JSeparator();
        EngineerIdxt4 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jSeparator32 = new javax.swing.JSeparator();
        jSeparator33 = new javax.swing.JSeparator();
        addressTxt4 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jSeparator34 = new javax.swing.JSeparator();
        jLabel49 = new javax.swing.JLabel();
        Builder_idTxt6 = new javax.swing.JTextField();
        jSeparator35 = new javax.swing.JSeparator();
        confirm5 = new javax.swing.JButton();
        jSeparator36 = new javax.swing.JSeparator();
        editEmployeeCard = new javax.swing.JPanel();
        viewInfoCard = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        viewBuilders = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        viewCustomers = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        viewEngineers = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        viewLabours = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RMS-Manger");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(java.awt.Color.white);
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button1.setBackground(java.awt.Color.white);
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button1MouseEntered(evt);
            }
        });
        button1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indicator1.setBackground(new java.awt.Color(119, 119, 119));

        javax.swing.GroupLayout indicator1Layout = new javax.swing.GroupLayout(indicator1);
        indicator1.setLayout(indicator1Layout);
        indicator1Layout.setHorizontalGroup(
            indicator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        indicator1Layout.setVerticalGroup(
            indicator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        button1.add(indicator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(33, 21, 21));
        jLabel1.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Home");
        button1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, 37));

        sidePanel.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 270, -1));

        buttonHome1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(119, 119, 119));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        buttonHome1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        sidePanel.add(buttonHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 197, -1, -1));

        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button2MouseEntered(evt);
            }
        });
        button2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indicator2.setBackground(new java.awt.Color(119, 119, 119));
        indicator2.setForeground(new java.awt.Color(119, 119, 119));

        javax.swing.GroupLayout indicator2Layout = new javax.swing.GroupLayout(indicator2);
        indicator2.setLayout(indicator2Layout);
        indicator2Layout.setHorizontalGroup(
            indicator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        indicator2Layout.setVerticalGroup(
            indicator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        button2.add(indicator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add Employee");
        button2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 0, 220, 37));

        sidePanel.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 270, -1));

        button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button4MouseEntered(evt);
            }
        });
        button4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indicator3.setBackground(new java.awt.Color(119, 119, 119));
        indicator3.setForeground(new java.awt.Color(119, 119, 119));

        javax.swing.GroupLayout indicator3Layout = new javax.swing.GroupLayout(indicator3);
        indicator3.setLayout(indicator3Layout);
        indicator3Layout.setHorizontalGroup(
            indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        indicator3Layout.setVerticalGroup(
            indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        button4.add(indicator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setBackground(java.awt.Color.white);
        jLabel5.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("View Employee Details");
        button4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 0, 230, 37));

        sidePanel.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 270, -1));

        jPanel1.setBackground(new java.awt.Color(119, 119, 119));

        jLabel6.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Manager Portal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        sidePanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 110));

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 507));

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(115, 115, 115));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 20)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Welcome");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 172, 45));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rms/icons/icons8-apartment-96.png"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 70));

        jLabel9.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 20)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Real Estate Management System");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 400, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 110));

        cardParent.setLayout(new java.awt.CardLayout());

        homeCard.setAlignmentX(1.0F);

        jLabel7.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 24)); // NOI18N
        jLabel7.setText("Personal Information");

        jSeparator1.setBackground(new java.awt.Color(1, 1, 1));
        jSeparator1.setForeground(java.awt.Color.black);
        jSeparator1.setAlignmentY(1.0F);
        jSeparator1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel5.setBackground(new java.awt.Color(216, 216, 216));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Name");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 76, 67, -1));

        jLabel13.setText("ID");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 111, 67, -1));

        jPanel6.setBackground(new java.awt.Color(56, 56, 56));
        jPanel6.setForeground(new java.awt.Color(254, 254, 254));

        lblName.setForeground(new java.awt.Color(254, 254, 254));
        lblName.setText("NAme");

        lblId.setForeground(new java.awt.Color(254, 254, 254));
        lblId.setText("ID");

        lblEmail.setForeground(new java.awt.Color(254, 254, 254));
        lblEmail.setText("Email");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblName)
                .addGap(18, 18, 18)
                .addComponent(lblId)
                .addGap(18, 18, 18)
                .addComponent(lblEmail)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 57, -1, 180));

        jLabel14.setText("Email");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        javax.swing.GroupLayout homeCardLayout = new javax.swing.GroupLayout(homeCard);
        homeCard.setLayout(homeCardLayout);
        homeCardLayout.setHorizontalGroup(
            homeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeCardLayout.createSequentialGroup()
                .addGroup(homeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(homeCardLayout.createSequentialGroup()
                        .addGroup(homeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        homeCardLayout.setVerticalGroup(
            homeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeCardLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardParent.add(homeCard, "card2");

        addEmployeeCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 24)); // NOI18N
        jLabel15.setText("ADD EMPLOYEE");
        addEmployeeCard.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 39, 221, 40));
        addEmployeeCard.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 220, 10));

        jLabel16.setText("Employee type");
        addEmployeeCard.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--", "Builder", "Engineer", "Customer", "Labour" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        addEmployeeCard.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        addEmpParent.setLayout(new java.awt.CardLayout());

        Engineer.setBackground(new java.awt.Color(115, 115, 115));
        Engineer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(254, 254, 254));
        jLabel38.setText("Name");
        Engineer.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        nameTxt6.setBackground(new java.awt.Color(115, 115, 115));
        nameTxt6.setForeground(new java.awt.Color(254, 254, 254));
        nameTxt6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nameTxt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxt6ActionPerformed(evt);
            }
        });
        Engineer.add(nameTxt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 210, 30));
        Engineer.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 210, -1));

        EngineerIdxt3.setBackground(new java.awt.Color(115, 115, 115));
        EngineerIdxt3.setForeground(new java.awt.Color(254, 254, 254));
        EngineerIdxt3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        EngineerIdxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngineerIdxt3ActionPerformed(evt);
            }
        });
        Engineer.add(EngineerIdxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 210, 30));

        jLabel39.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(254, 254, 254));
        jLabel39.setText("Engineer ID");
        Engineer.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));
        Engineer.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 210, -1));

        emailTxt4.setBackground(new java.awt.Color(115, 115, 115));
        emailTxt4.setForeground(new java.awt.Color(254, 254, 254));
        emailTxt4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        emailTxt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxt4ActionPerformed(evt);
            }
        });
        Engineer.add(emailTxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 210, 30));

        jLabel41.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(254, 254, 254));
        jLabel41.setText("Email");
        Engineer.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel42.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(254, 254, 254));
        jLabel42.setText("Contact");
        Engineer.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        nameTxt7.setBackground(new java.awt.Color(115, 115, 115));
        nameTxt7.setForeground(new java.awt.Color(254, 254, 254));
        nameTxt7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nameTxt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxt7ActionPerformed(evt);
            }
        });
        Engineer.add(nameTxt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 210, 30));
        Engineer.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 210, 10));

        addressTxt3.setBackground(new java.awt.Color(115, 115, 115));
        addressTxt3.setForeground(new java.awt.Color(254, 254, 254));
        addressTxt3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addressTxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxt3ActionPerformed(evt);
            }
        });
        Engineer.add(addressTxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 210, 30));

        jLabel43.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(254, 254, 254));
        jLabel43.setText("Address");
        Engineer.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));
        Engineer.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 210, 10));

        jLabel44.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(254, 254, 254));
        jLabel44.setText("Builder ID");
        Engineer.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        Builder_idTxt5.setBackground(new java.awt.Color(115, 115, 115));
        Builder_idTxt5.setForeground(new java.awt.Color(254, 254, 254));
        Builder_idTxt5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Builder_idTxt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Builder_idTxt5ActionPerformed(evt);
            }
        });
        Engineer.add(Builder_idTxt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 210, 30));
        Engineer.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 210, -1));

        confirm4.setBackground(new java.awt.Color(0, 128, 255));
        confirm4.setForeground(java.awt.Color.white);
        confirm4.setText("Confirm");
        confirm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm4ActionPerformed(evt);
            }
        });
        Engineer.add(confirm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 130, -1));
        Engineer.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 210, 10));

        addEmpParent.add(Engineer, "card2");

        Customer.setBackground(new java.awt.Color(115, 115, 115));
        Customer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameTxt10.setBackground(new java.awt.Color(115, 115, 115));
        nameTxt10.setForeground(new java.awt.Color(254, 254, 254));
        nameTxt10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nameTxt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxt10ActionPerformed(evt);
            }
        });
        Customer.add(nameTxt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 210, 30));

        emailTxt6.setBackground(new java.awt.Color(115, 115, 115));
        emailTxt6.setForeground(new java.awt.Color(254, 254, 254));
        emailTxt6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        emailTxt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxt6ActionPerformed(evt);
            }
        });
        Customer.add(emailTxt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 210, 30));

        flatnoTXT.setBackground(new java.awt.Color(115, 115, 115));
        flatnoTXT.setForeground(new java.awt.Color(254, 254, 254));
        flatnoTXT.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        flatnoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flatnoTXTActionPerformed(evt);
            }
        });
        Customer.add(flatnoTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 210, 30));

        jLabel50.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(254, 254, 254));
        jLabel50.setText("Flat Number");
        Customer.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel51.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(254, 254, 254));
        jLabel51.setText("Email");
        Customer.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel52.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(254, 254, 254));
        jLabel52.setText("Name");
        Customer.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        Customer.add(jSeparator37, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 210, -1));

        customerIdtxt.setBackground(new java.awt.Color(115, 115, 115));
        customerIdtxt.setForeground(new java.awt.Color(254, 254, 254));
        customerIdtxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        customerIdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdtxtActionPerformed(evt);
            }
        });
        Customer.add(customerIdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 210, 30));

        jLabel53.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(254, 254, 254));
        jLabel53.setText("Customer ID");
        Customer.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));
        Customer.add(jSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 210, -1));
        Customer.add(jSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 210, 10));

        projectIdTxt.setBackground(new java.awt.Color(115, 115, 115));
        projectIdTxt.setForeground(new java.awt.Color(254, 254, 254));
        projectIdTxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        projectIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectIdTxtActionPerformed(evt);
            }
        });
        Customer.add(projectIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 210, 30));

        jLabel54.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(254, 254, 254));
        jLabel54.setText("Project ID");
        Customer.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));
        Customer.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 210, 10));

        jLabel55.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(254, 254, 254));
        jLabel55.setText("Project ID");
        Customer.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        projectIdtxt.setBackground(new java.awt.Color(115, 115, 115));
        projectIdtxt.setForeground(new java.awt.Color(254, 254, 254));
        projectIdtxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        projectIdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectIdtxtActionPerformed(evt);
            }
        });
        Customer.add(projectIdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 210, 30));
        Customer.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 210, -1));

        confirm6.setBackground(new java.awt.Color(0, 128, 255));
        confirm6.setForeground(java.awt.Color.white);
        confirm6.setText("Confirm");
        confirm6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm6ActionPerformed(evt);
            }
        });
        Customer.add(confirm6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 130, -1));
        Customer.add(jSeparator42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 210, 10));

        addEmpParent.add(Customer, "card4");

        Labour.setBackground(new java.awt.Color(115, 115, 115));
        Labour.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Builder1.setBackground(new java.awt.Color(115, 115, 115));
        Builder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameTxt11.setBackground(new java.awt.Color(115, 115, 115));
        nameTxt11.setForeground(new java.awt.Color(254, 254, 254));
        nameTxt11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nameTxt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxt11ActionPerformed(evt);
            }
        });
        Builder1.add(nameTxt11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 210, 30));

        emailTxt7.setBackground(new java.awt.Color(115, 115, 115));
        emailTxt7.setForeground(new java.awt.Color(254, 254, 254));
        emailTxt7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        emailTxt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxt7ActionPerformed(evt);
            }
        });
        Builder1.add(emailTxt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 210, 30));

        jLabel57.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(254, 254, 254));
        jLabel57.setText("Engineer ID");
        Builder1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jLabel58.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(254, 254, 254));
        jLabel58.setText("Name");
        Builder1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        Builder1.add(jSeparator43, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 210, -1));

        EngineerIdxt5.setBackground(new java.awt.Color(115, 115, 115));
        EngineerIdxt5.setForeground(new java.awt.Color(254, 254, 254));
        EngineerIdxt5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        EngineerIdxt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngineerIdxt5ActionPerformed(evt);
            }
        });
        Builder1.add(EngineerIdxt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 210, 30));

        jLabel59.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(254, 254, 254));
        jLabel59.setText("Labour ID");
        Builder1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));
        Builder1.add(jSeparator44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 210, -1));
        Builder1.add(jSeparator45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 210, 10));
        Builder1.add(jSeparator46, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 210, 10));

        Builder_idTxt7.setBackground(new java.awt.Color(115, 115, 115));
        Builder_idTxt7.setForeground(new java.awt.Color(254, 254, 254));
        Builder_idTxt7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Builder_idTxt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Builder_idTxt7ActionPerformed(evt);
            }
        });
        Builder1.add(Builder_idTxt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 210, 30));

        confirm7.setBackground(new java.awt.Color(0, 128, 255));
        confirm7.setForeground(java.awt.Color.white);
        confirm7.setText("Confirm");
        confirm7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm7ActionPerformed(evt);
            }
        });
        Builder1.add(confirm7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 130, -1));

        jLabel60.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(254, 254, 254));
        jLabel60.setText("Unit Number");
        Builder1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        Labour.add(Builder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        addEmpParent.add(Labour, "card5");

        Builder.setBackground(new java.awt.Color(115, 115, 115));
        Builder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameTxt8.setBackground(new java.awt.Color(115, 115, 115));
        nameTxt8.setForeground(new java.awt.Color(254, 254, 254));
        nameTxt8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nameTxt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxt8ActionPerformed(evt);
            }
        });
        Builder.add(nameTxt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 210, 30));

        emailTxt5.setBackground(new java.awt.Color(115, 115, 115));
        emailTxt5.setForeground(new java.awt.Color(254, 254, 254));
        emailTxt5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        emailTxt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxt5ActionPerformed(evt);
            }
        });
        Builder.add(emailTxt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 210, 30));

        nameTxt9.setBackground(new java.awt.Color(115, 115, 115));
        nameTxt9.setForeground(new java.awt.Color(254, 254, 254));
        nameTxt9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nameTxt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxt9ActionPerformed(evt);
            }
        });
        Builder.add(nameTxt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 210, 30));

        jLabel45.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(254, 254, 254));
        jLabel45.setText("Contact");
        Builder.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel46.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(254, 254, 254));
        jLabel46.setText("Email");
        Builder.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel40.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(254, 254, 254));
        jLabel40.setText("Name");
        Builder.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        Builder.add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 210, -1));

        EngineerIdxt4.setBackground(new java.awt.Color(115, 115, 115));
        EngineerIdxt4.setForeground(new java.awt.Color(254, 254, 254));
        EngineerIdxt4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        EngineerIdxt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngineerIdxt4ActionPerformed(evt);
            }
        });
        Builder.add(EngineerIdxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 210, 30));

        jLabel47.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(254, 254, 254));
        jLabel47.setText("Builder ID");
        Builder.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));
        Builder.add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 210, -1));
        Builder.add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 210, 10));

        addressTxt4.setBackground(new java.awt.Color(115, 115, 115));
        addressTxt4.setForeground(new java.awt.Color(254, 254, 254));
        addressTxt4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addressTxt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxt4ActionPerformed(evt);
            }
        });
        Builder.add(addressTxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 210, 30));

        jLabel48.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(254, 254, 254));
        jLabel48.setText("Address");
        Builder.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));
        Builder.add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 210, 10));

        jLabel49.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(254, 254, 254));
        jLabel49.setText("Project ID");
        Builder.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        Builder_idTxt6.setBackground(new java.awt.Color(115, 115, 115));
        Builder_idTxt6.setForeground(new java.awt.Color(254, 254, 254));
        Builder_idTxt6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Builder_idTxt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Builder_idTxt6ActionPerformed(evt);
            }
        });
        Builder.add(Builder_idTxt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 210, 30));
        Builder.add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 210, -1));

        confirm5.setBackground(new java.awt.Color(0, 128, 255));
        confirm5.setForeground(java.awt.Color.white);
        confirm5.setText("Confirm");
        confirm5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm5ActionPerformed(evt);
            }
        });
        Builder.add(confirm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 130, -1));
        Builder.add(jSeparator36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 210, 10));

        addEmpParent.add(Builder, "card3");

        addEmployeeCard.add(addEmpParent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 710, 250));

        cardParent.add(addEmployeeCard, "card3");

        javax.swing.GroupLayout editEmployeeCardLayout = new javax.swing.GroupLayout(editEmployeeCard);
        editEmployeeCard.setLayout(editEmployeeCardLayout);
        editEmployeeCardLayout.setHorizontalGroup(
            editEmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        editEmployeeCardLayout.setVerticalGroup(
            editEmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        cardParent.add(editEmployeeCard, "card5");

        viewInfoCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 24)); // NOI18N
        jLabel17.setText("VIEW INFORMATION");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Builder", "Customer", "Engineers", "Labours" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jLabel18.setText("Employee type");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel17))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel17)
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)))
        );

        viewInfoCard.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 710, 100));

        jPanel8.setLayout(new java.awt.CardLayout());

        viewBuilders.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBorder(null);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Builder ID", "Project ID", "Email ID", "Contact No."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        viewBuilders.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 12, 690, 268));

        jPanel8.add(viewBuilders, "card3");

        jTable2.setBorder(null);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Customer ID", "Project ID", "Flat No", "Email", "Dues"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout viewCustomersLayout = new javax.swing.GroupLayout(viewCustomers);
        viewCustomers.setLayout(viewCustomersLayout);
        viewCustomersLayout.setHorizontalGroup(
            viewCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(viewCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(viewCustomersLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        viewCustomersLayout.setVerticalGroup(
            viewCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
            .addGroup(viewCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(viewCustomersLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel8.add(viewCustomers, "card4");

        jTable3.setBorder(null);
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Engineer ID", "Builder ID", "Email ID", "Contact No."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout viewEngineersLayout = new javax.swing.GroupLayout(viewEngineers);
        viewEngineers.setLayout(viewEngineersLayout);
        viewEngineersLayout.setHorizontalGroup(
            viewEngineersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(viewEngineersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(viewEngineersLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        viewEngineersLayout.setVerticalGroup(
            viewEngineersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
            .addGroup(viewEngineersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(viewEngineersLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel8.add(viewEngineers, "card5");

        jTable4.setBorder(null);
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Labour ID", "Unit Number", "Engineer ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout viewLaboursLayout = new javax.swing.GroupLayout(viewLabours);
        viewLabours.setLayout(viewLaboursLayout);
        viewLaboursLayout.setHorizontalGroup(
            viewLaboursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(viewLaboursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(viewLaboursLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        viewLaboursLayout.setVerticalGroup(
            viewLaboursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
            .addGroup(viewLaboursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(viewLaboursLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel8.add(viewLabours, "card2");

        viewInfoCard.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 700, 280));

        cardParent.add(viewInfoCard, "card4");

        jPanel3.add(cardParent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 710, 400));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 710, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseEntered
        // TODO add your handling code here:
        onHover(button2);
        onLeaveHover(button1);
//        onLeaveHover(button3);
        onLeaveHover(button4);
    }//GEN-LAST:event_button2MouseEntered

    private void button4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MouseExited
        // TODO add your handling code here:
        onLeaveHover(button4);
    }//GEN-LAST:event_button4MouseExited

    private void button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseEntered
        // TODO add your handling code here:
        onHover(button1);
        onLeaveHover(button2);
//        onLeaveHover(button3);
        onLeaveHover(button4);
        indicator1.setOpaque(false);
        indicator2.setOpaque(true);
        indicator3.setOpaque(true);
        
        
    }//GEN-LAST:event_button1MouseEntered

    private void button4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MouseEntered

        onHover(button4);
//        onLeaveHover(button3);
        onLeaveHover(button1);
        onLeaveHover(button2);

    }//GEN-LAST:event_button4MouseEntered

    private void button2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseExited
        // TODO add your handling code here:
        onLeaveHover(button2);
    }//GEN-LAST:event_button2MouseExited

    private void button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseExited
        // TODO add your handling code here:
        onLeaveHover(button1);
    }//GEN-LAST:event_button1MouseExited

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        // TODO add your handling code here:
        viewInfoCard.setVisible(false);
        addEmployeeCard.setVisible(false);
        homeCard.setVisible(true);
        
            
    }//GEN-LAST:event_button1MouseClicked

    private void nameTxt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxt6ActionPerformed

    private void EngineerIdxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngineerIdxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EngineerIdxt3ActionPerformed

    private void emailTxt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxt4ActionPerformed

    private void nameTxt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxt7ActionPerformed

    private void addressTxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTxt3ActionPerformed

    private void Builder_idTxt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Builder_idTxt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Builder_idTxt5ActionPerformed

    private void confirm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm4ActionPerformed

    private void nameTxt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxt8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxt8ActionPerformed

    private void emailTxt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxt5ActionPerformed

    private void nameTxt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxt9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxt9ActionPerformed

    private void EngineerIdxt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngineerIdxt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EngineerIdxt4ActionPerformed

    private void addressTxt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTxt4ActionPerformed

    private void Builder_idTxt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Builder_idTxt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Builder_idTxt6ActionPerformed

    private void confirm5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm5ActionPerformed

    private void nameTxt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxt10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxt10ActionPerformed

    private void emailTxt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxt6ActionPerformed

    private void flatnoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flatnoTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flatnoTXTActionPerformed

    private void customerIdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIdtxtActionPerformed

    private void projectIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectIdTxtActionPerformed

    private void projectIdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectIdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectIdtxtActionPerformed

    private void confirm6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm6ActionPerformed

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseClicked
        // TODO add your handling code here:
        homeCard.setVisible(false);
        addEmployeeCard.setVisible(true);
        viewInfoCard.setVisible(false);
        indicator1.setOpaque(true);
        indicator2.setOpaque(false);
        indicator3.setOpaque(true);
        
    }//GEN-LAST:event_button2MouseClicked

    private void button4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MouseClicked
        // TODO add your handling code here:
        homeCard.setVisible(false);
        addEmployeeCard.setVisible(false);
        viewInfoCard.setVisible(true);
        indicator1.setOpaque(true);
        indicator2.setOpaque(true);
        indicator3.setOpaque(false);
    }//GEN-LAST:event_button4MouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        int index=jComboBox1.getSelectedIndex();
        if(index==1){
            Builder.setVisible(true);
            Engineer.setVisible(false);
            Customer.setVisible(false);
            Labour.setVisible(false);
        }
        else if(index==2){
            Builder.setVisible(false);
            Engineer.setVisible(true);
            Customer.setVisible(false);
            Labour.setVisible(false);

        }
        else if(index==3){
             Builder.setVisible(false);
            Engineer.setVisible(false);
            Customer.setVisible(true);
            Labour.setVisible(false);
        }
        else if(index==4){
            Builder.setVisible(false);
            Engineer.setVisible(false);
            Customer.setVisible(false);
            Labour.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void nameTxt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxt11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxt11ActionPerformed

    private void emailTxt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxt7ActionPerformed

    private void EngineerIdxt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngineerIdxt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EngineerIdxt5ActionPerformed

    private void Builder_idTxt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Builder_idTxt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Builder_idTxt7ActionPerformed

    private void confirm7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm7ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
         int index=jComboBox2.getSelectedIndex();
        if(index==0){
            viewCustomers.setVisible(false);
            viewBuilders.setVisible(true);
            viewEngineers.setVisible(false);
            viewLabours.setVisible(false);
        }
        else if(index==1){
            viewCustomers.setVisible(true);
            viewBuilders.setVisible(false);
            viewEngineers.setVisible(false);
            viewLabours.setVisible(false);
        }
        else if(index==2){
            viewCustomers.setVisible(false);
            viewBuilders.setVisible(false);
            viewEngineers.setVisible(true);
            viewLabours.setVisible(false);
        }
        else if(index==3){
            viewCustomers.setVisible(false);
            viewBuilders.setVisible(false);
            viewEngineers.setVisible(false);
            viewLabours.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    
    void onHover(JPanel jp){
        jp.setBackground(new Color(220,220,220));
    }
    void onLeaveHover(JPanel jp){
        jp.setBackground(Color.white);
    }
    void onClick(JPanel jp){
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerHome("ivedantlodha@gmail.com").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Builder;
    private javax.swing.JPanel Builder1;
    private javax.swing.JTextField Builder_idTxt5;
    private javax.swing.JTextField Builder_idTxt6;
    private javax.swing.JTextField Builder_idTxt7;
    private javax.swing.JPanel Customer;
    private javax.swing.JPanel Engineer;
    private javax.swing.JTextField EngineerIdxt3;
    private javax.swing.JTextField EngineerIdxt4;
    private javax.swing.JTextField EngineerIdxt5;
    private javax.swing.JPanel Labour;
    private javax.swing.JPanel addEmpParent;
    private javax.swing.JPanel addEmployeeCard;
    private javax.swing.JTextField addressTxt3;
    private javax.swing.JTextField addressTxt4;
    private javax.swing.JPanel button1;
    private javax.swing.JPanel button2;
    private javax.swing.JPanel button4;
    private javax.swing.JPanel buttonHome1;
    private javax.swing.JPanel cardParent;
    private javax.swing.JButton confirm4;
    private javax.swing.JButton confirm5;
    private javax.swing.JButton confirm6;
    private javax.swing.JButton confirm7;
    private javax.swing.JTextField customerIdtxt;
    private javax.swing.JPanel editEmployeeCard;
    private javax.swing.JTextField emailTxt4;
    private javax.swing.JTextField emailTxt5;
    private javax.swing.JTextField emailTxt6;
    private javax.swing.JTextField emailTxt7;
    private javax.swing.JTextField flatnoTXT;
    private javax.swing.JPanel homeCard;
    private javax.swing.JPanel indicator1;
    private javax.swing.JPanel indicator2;
    private javax.swing.JPanel indicator3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator43;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator45;
    private javax.swing.JSeparator jSeparator46;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField nameTxt10;
    private javax.swing.JTextField nameTxt11;
    private javax.swing.JTextField nameTxt6;
    private javax.swing.JTextField nameTxt7;
    private javax.swing.JTextField nameTxt8;
    private javax.swing.JTextField nameTxt9;
    private javax.swing.JTextField projectIdTxt;
    private javax.swing.JTextField projectIdtxt;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel viewBuilders;
    private javax.swing.JPanel viewCustomers;
    private javax.swing.JPanel viewEngineers;
    private javax.swing.JPanel viewInfoCard;
    private javax.swing.JPanel viewLabours;
    // End of variables declaration//GEN-END:variables
}
